### ISSUE TITLE
neither <stdint.h> nor <inttypes.h> found, aborting

### ISSUE THREAD

**Issue by dcy** [vinoski/erlsha2#14]
os: ubuntu 16.04
erl version:otp 19
rebar3 version: 3.3.6
```rebar3 release``` can not work.
```

``` dcy@dcy-dcy  ~/app/eqsms  ./rebar3 release        
===> Verifying dependencies...
===> Compiling erlsha2
neither <stdint.h> nor <inttypes.h> found, aborting
===> Hook for compile failed!

**Comment by vinoski** [comment]
Before I address the issue, I'll note that if you're running Erlang/OTP 19, you don't need `erlsha2` since the standard `crypto` module provides everything provided here.

You can get `<stdint.h>` on Ubuntu 16.04 via

    apt-get install libc6-dev

You might need to run `apt-get update` first so that `libc6-dev` is available for installation.
